# Build a cron job to create a umi project which use antd and dumi, and then build it.
name: Mock Project Build

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

# Cancel prev CI if new commit come
concurrency:
  group: unique
  cancel-in-progress: true

jobs:
  pr-check-ci:
    runs-on: ubuntu-latest
    name: Build Project
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run Script
        run: bash ./scripts/ci-mock-project-build.sh

      - uses: actions/cache/save@v3
        with:
          path: ~tmpProj/yarn.lock
          key: lock-file

      ##################################################################
      ##                        Diff Lock File                        ##
      ##################################################################
      - name: Rename failed lock file
        if: ${{ failure() }}
        run: |
          if [ -f ~tmpProj/yarn.lock ]; then
            mv ~tmpProj/yarn.lock ~tmpProj/yarn.lock.failed
          fi

      - name: Download success lock file as `success.lock`
        if: ${{ failure() }}
        uses: actions/cache/restore@v3
        with:
          path: ~tmpProj/yarn.lock
          key: lock-file

      - name: diff if filed
        if: ${{ failure() }}
        run: |
          if [ -f ~tmpProj/yarn.lock ]; then
            npx diff-yarn-lock ~tmpProj/yarn.lock ~tmpProj/yarn.lock.failed
          fi

      - uses: actions-cool/ci-notice@v1
        if: ${{ failure() }}
        with:
          notice-types: 'dingding'
          dingding-token: ${{ secrets.DINGDING_BOT_COLLABORATOR_TOKEN }}
          notice-title: 'CI Mock Project Build Failed'
